# Generated by Django 5.1.6 on 2025-02-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipo",
            name="serial_equipo",
        ),
    ]
