# Generated by Django 5.1.6 on 2025-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="costo_unitario",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="disco_duro",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="equipo",
            name="marca",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="equipo",
            name="procesador",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="equipo",
            name="proveedor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="equipo",
            name="ram",
            field=models.CharField(default="Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="equipo",
            name="serial_equipo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
