# Generated by Django 5.1.6 on 2025-02-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0002_remove_equipo_serial_equipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proveedor", models.CharField(max_length=100)),
                ("num_contrato", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contrato",
            },
        ),
        migrations.AddField(
            model_name="equipo",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipmentInventory.contrato",
            ),
        ),
    ]
