# Generated by Django 5.1.6 on 2025-02-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipmentInventory",
            "0002_equipo_costo_unitario_equipo_disco_duro_equipo_marca_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="disco_duro",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="marca",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="procesador",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="ram",
            field=models.CharField(max_length=100),
        ),
    ]
