# Generated by Django 5.1.6 on 2025-02-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipmentInventory",
            "0003_alter_equipo_disco_duro_alter_equipo_marca_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sede",
            name="empresa",
        ),
        migrations.AlterField(
            model_name="equipo",
            name="costo_unitario",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="proveedor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="equipo",
            name="serial_equipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="EmpresaSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipmentInventory.empresa",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipmentInventory.sede",
                    ),
                ),
            ],
            options={
                "unique_together": {("empresa", "sede")},
            },
        ),
    ]
