# Generated by Django 5.1.6 on 2025-03-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0003_contrato_equipo_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="centro_costo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
