# Generated by Django 5.1.6 on 2025-03-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0004_usuario_centro_costo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="centro_costo",
        ),
        migrations.AddField(
            model_name="area",
            name="centro_costo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
