# Generated by Django 5.1.6 on 2025-02-11 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipmentInventory",
            "0004_remove_sede_empresa_alter_equipo_costo_unitario_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"verbose_name": "Área", "verbose_name_plural": "Áreas"},
        ),
        migrations.AlterModelOptions(
            name="departamento",
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="empresa",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterModelOptions(
            name="empresasede",
            options={
                "verbose_name": "Empresa - Sede",
                "verbose_name_plural": "Empresas - Sedes",
            },
        ),
        migrations.AlterModelOptions(
            name="equipo",
            options={"verbose_name": "Equipo", "verbose_name_plural": "Equipos"},
        ),
        migrations.AlterModelOptions(
            name="estado",
            options={"verbose_name": "Estado", "verbose_name_plural": "Estados"},
        ),
        migrations.AlterModelOptions(
            name="historialasignaciones",
            options={
                "verbose_name": "Historial de Asignación",
                "verbose_name_plural": "Historial de Asignaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="sede",
            options={"verbose_name": "Sede", "verbose_name_plural": "Sedes"},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.RemoveField(
            model_name="area",
            name="sede",
        ),
        migrations.RemoveField(
            model_name="departamento",
            name="area",
        ),
        migrations.AddField(
            model_name="usuario",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipmentInventory.sede",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="empresasede",
            name="sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipmentInventory.sede",
            ),
        ),
        migrations.AlterField(
            model_name="sede",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="AreaSede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipmentInventory.area",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipmentInventory.sede",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área - Sede",
                "verbose_name_plural": "Áreas - Sedes",
                "unique_together": {("area", "sede")},
            },
        ),
        migrations.AddField(
            model_name="departamento",
            name="area_sede",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="equipmentInventory.areasede",
            ),
        ),
    ]
