# Generated by Django 5.1.6 on 2025-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0005_remove_usuario_centro_costo_area_centro_costo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="usuario",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
