# Generated by Django 5.1.6 on 2025-03-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0006_alter_equipo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="mombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
