# Generated by Django 5.1.6 on 2025-03-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0007_equipo_mombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipo",
            old_name="mombre",
            new_name="nombre",
        ),
    ]
