# Generated by Django 5.1.6 on 2025-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0008_rename_mombre_equipo_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="cantidad_equipos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contrato",
            name="fecha_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
