# Generated by Django 5.1.6 on 2025-03-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0009_contrato_cantidad_equipos_contrato_fecha_inicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True),
        ),
    ]
