# Generated by Django 5.1.6 on 2025-03-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0010_contrato_fecha_fin"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="estado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
