# Generated by Django 5.1.6 on 2025-03-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0011_contrato_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipmentInventory.departamento",
            ),
        ),
    ]
