# Generated by Django 5.1.6 on 2025-03-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0012_equipo_departamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipo",
            name="departamento",
        ),
        migrations.AddField(
            model_name="equipo",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipmentInventory.area",
            ),
        ),
    ]
