# Generated by Django 5.1.6 on 2025-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0013_remove_equipo_departamento_equipo_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="costo_unitario",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
