# Generated by Django 5.1.6 on 2025-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0014_alter_equipo_costo_unitario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="costo_unitario",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
