# Generated by Django 5.1.6 on 2025-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipmentInventory", "0015_alter_equipo_costo_unitario"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="costo_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
